### ISSUE TITLE
tuning problems ahead

### ISSUE THREAD

**Issue by goord** [microhh/rte-rrtmgp-cpp#7]
changing the block sizes ``block_lay_min`` and ``block_col_min`` in the ``compute_tau_absorption`` function that launches the ``compute_tau_minor_absorption_kernel`` yields a different result for the allsky test case.

**Comment by goord** [comment]
It seems it's changing the layer block size which causes differences. Since the kernel launching parameters look fine to me, I suspect a race condition inside the ``compute_tau_minor_absorption_kernel``

**Comment by isazi** [comment]
Can happen when the code was not thought to be tunable from the beginning. May need some reworking of the code to adapt to external parameters.

**Comment by MennoVeerman** [comment]
What combinations of block_lay_min and block_col_min did you test? I only find different results when the block_lay_min x block_col_min is larger than 1024, the max. number of threads per block.
